import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getBooks, getAuthor } from './booksAPI';

const initialState = {
  data: [],
  loading: false,
  author: {},
  authorLoading: false,
};

export const getBooksAsync = createAsyncThunk(
  'books/getBooks',
  async (q, page) => {
    const response = await getBooks(q[0], q[1]);
    return response.data;
  }
)

export const getAuthorAsync = createAsyncThunk(
  'author/getAuthor',
  async (key) => {
    const response = await getAuthor(key);
    return response.data;
  }
)

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
    },
    decrement: (state) => {
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action) => {
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getAuthorAsync.pending, (state) => {
        state.authorLoading = true;
      })
      .addCase(getAuthorAsync.fulfilled, (state, action) => {
        state.authorLoading = false;
        state.author = action.payload;
      })
      .addCase(getBooksAsync.pending, (state) => {
        state.loading = true;
      })
      .addCase(getBooksAsync.fulfilled, (state, action) => {
        state.loading = false;
        state.data = action.payload.docs;
      });
  },
});

export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectData = (state) => state.counter.data;
export const selectDataLoading = (state) => state.counter.loading;
export const selectAuthor = (state) => state.counter.author;
export const selectAuthorLoading = (state) => state.counter.authorLoading;

export default counterSlice.reducer;
